### ISSUE TITLE
Ressource folder to share documents

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-website#1]
Long ago, I had started some tests to build a website dedicated to Geotrek community - http://www.cmonchicourt.fr/TESTS/GEOTREK/

Never finished as I thought it would be better to have everything at the same place. 

I think about sharing this document - http://www.cmonchicourt.fr/TESTS/GEOTREK/fichiers/files/STAGES/Rapport%20final_Felix_Merzeau_Geotrek.pdf

But I also have other internships reports, presentations...

Is is OK if I create a /ressources/ folder in this Git project and upload some documents inside. At least to be able to send links to these files when someone need it ? 

In a second time, we can create a RESSOURCE tab in the website, with links to some articles and documents as I started here - http://www.cmonchicourt.fr/TESTS/GEOTREK/ressources.html

**Comment by camillemonchicourt** [comment]
I would like to start uploading documents in a /ressources/ folder if it is OK for you. 
But not sure where I should do my PR, in master or gh-pages branch ?

Thanks.

**Comment by SBats** [comment]
Mm not sure about this. The website may not be the better place to put resources about the product. If it concerns a specific part (rando, admin, mobile), it should go with the doc of the one concerned. Otherwise, I'm not sure. What do you think guys ?

**Comment by camillemonchicourt** [comment]
Yes maybe it is not the place. But it is what I am sending all the time (PDF, links, presentations...) and it is not only some documentations. Also they have troubles to understand the project globally so not sure it could go in each project. Also I am not sure, that I want to make the Github projects growing with some 15 Mo PDF and things like that, that user will download each time they want to install or update Geotrek. 

Let's keep thinking about the right way to do that.

**Comment by camillemonchicourt** [comment]
It was discussed and decided that the github project was not the right place to host big PDF files so the files are hosted on another WEB host and a RESSOURCE page has been created (https://github.com/GeotrekCE/Geotrek-website/pull/12) with links to distant files.
